### ISSUE TITLE
resulting TTF glyphs have too much padding

### ISSUE THREAD

**Issue by sunaku** [koron/bdf2ttf#2]
Hello,

After installing TTF files generated by bdf2ttf (provided by you in issue #1) under Windows 7, I observed:

![screenshot](http://i.imgur.com/bjwGixC.png)

There is too much space between each glyph. :cold_sweat:  Is there a way to correct this?  Perhaps in the INI file?

Thanks for your consideration.

**Comment by koron** [comment]
It may caused by considering double width char.
bdf2ttf supports double width char for KANJI or so.

I guess some algorithm for double width chars, do it.
But sorry, I forget details, this project is too old for me.

**Comment by koron** [comment]
It may be caused by https://github.com/koron/bdf2ttf/blob/007ee8ee718aee758bae3ef2a077ae2b903a09b4/src/bdf.c#L390-L391

**Comment by koron** [comment]
@sunaku There are no property to change this in config file. 
And I don't want to change current behavior.

Can you fix your BDF files?
Width of each glyph is detemined by font size and its glypy pixel width [as I pointed](https://github.com/koron/bdf2ttf/blob/007ee8ee718aee758bae3ef2a077ae2b903a09b4/src/bdf.c#L390-L391).
So it may be fixed by changing BDF file.

**Comment by sunaku** [comment]
Sorry for the trouble. :sweat_smile: Yes, I will adjust my BDF files instead.

**Comment by koron** [comment]
@sunaku Can you close this issue?

**Comment by sunaku** [comment]
Done, thanks for your help! :bow:
